'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Public Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("GrapeCity.ActiveReports.Samples.CustomWpfPreview.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Custom WPF Preview.
        '''</summary>
        Public ReadOnly Property AplicationTitle() As String
            Get
                Return ResourceManager.GetString("AplicationTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Copy.
        '''</summary>
        Public ReadOnly Property CopyMenu() As String
            Get
                Return ResourceManager.GetString("CopyMenu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Decrease Zoom.
        '''</summary>
        Public ReadOnly Property DecreaseZoomMenu() As String
            Get
                Return ResourceManager.GetString("DecreaseZoomMenu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to E_xit.
        '''</summary>
        Public ReadOnly Property ExitMenu() As String
            Get
                Return ResourceManager.GetString("ExitMenu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to File.
        '''</summary>
        Public ReadOnly Property FileMenu() As String
            Get
                Return ResourceManager.GetString("FileMenu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to First Page.
        '''</summary>
        Public ReadOnly Property FirstPageMenu() As String
            Get
                Return ResourceManager.GetString("FirstPageMenu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Increase Zoom.
        '''</summary>
        Public ReadOnly Property IncreaseZoomMenu() As String
            Get
                Return ResourceManager.GetString("IncreaseZoomMenu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Last Page.
        '''</summary>
        Public ReadOnly Property LastPageMenu() As String
            Get
                Return ResourceManager.GetString("LastPageMenu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to NextPage.
        '''</summary>
        Public ReadOnly Property NextPageMenu() As String
            Get
                Return ResourceManager.GetString("NextPageMenu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;Microsoft XPS Document Writer&apos; was not found. Please install to continue..
        '''</summary>
        Public ReadOnly Property NoXpsPrinterError() As String
            Get
                Return ResourceManager.GetString("NoXpsPrinterError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Open....
        '''</summary>
        Public ReadOnly Property OpenMenu() As String
            Get
                Return ResourceManager.GetString("OpenMenu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Previous Page.
        '''</summary>
        Public ReadOnly Property PrevPageMenu() As String
            Get
                Return ResourceManager.GetString("PrevPageMenu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Print....
        '''</summary>
        Public ReadOnly Property PrintMenu() As String
            Get
                Return ResourceManager.GetString("PrintMenu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reports (*.rdlx)|*.rdlx|All (*.*)|*.*.
        '''</summary>
        Public ReadOnly Property ReportFilesFilter() As String
            Get
                Return ResourceManager.GetString("ReportFilesFilter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to View.
        '''</summary>
        Public ReadOnly Property ViewMenu() As String
            Get
                Return ResourceManager.GetString("ViewMenu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Microsoft XPS Document Writer.
        '''</summary>
        Public ReadOnly Property XpsPrinterName() As String
            Get
                Return ResourceManager.GetString("XpsPrinterName", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
